
CREATE TABLE COUPON
(
  COUPON_UID        VARCHAR(100) NOT NULL COMMENT '쿠폰UID',
  COUPON_FILE       VARCHAR(100) NULL     COMMENT '쿠폰첨부파일',
  COUPON_NAME       VARCHAR(100) NOT NULL COMMENT '쿠폰이름',
  COUPON_DATE       VARCHAR(100) NOT NULL COMMENT '쿠폰작성일',
  COUPON_DATATIME1  VARCHAR(100) NOT NULL COMMENT '쿠폰기한1',
  COUPON_DATETIME2  VARCHAR(100) NOT NULL COMMENT '쿠폰기한2',
  ATTACHFILE_SEQ    VARCHAR(100) NULL     COMMENT '첨부파일일련번호',
  ORIGINALFILE_NAME VARCHAR(100) NULL     COMMENT '원본파일명',
  PHYSICALFILE_NAME VARCHAR(100) NULL     COMMENT '첨부파일명',
  PRIMARY KEY (COUPON_UID)
) COMMENT '쿠폰';
