
CREATE TABLE EVENT
(
  EVENT_UID      VARCHAR(100) NOT NULL COMMENT '이벤트게시판UID',
  EVENT_DATETIME VARCHAR(100) NULL     COMMENT '이벤트기간',
  EVENT_FILE     VARCHAR(100) NULL     COMMENT '이벤트첨부파일',
  EVENT_TITLE    VARCHAR(100) NOT NULL COMMENT '이벤트제목',
  EVENT_DATE     VARCHAR(100) NOT NULL COMMENT '이벤트작성일',
  EVENT_CONTENT  VARCHAR(100) NOT NULL COMMENT '이벤트내용',
  PRIMARY KEY (EVENT_UID)
) COMMENT '이벤트';
