
CREATE TABLE QNA
(
  QNA_UID         VARCHAR(100) NOT NULL COMMENT '문의내역UID',
  QNA_TITLE       VARCHAR(100) NULL     COMMENT '문의내역 제목',
  QNA_CONTENT     VARCHAR(100) NULL     COMMENT '문의내역 내용',
  QNA_DATE        VARCHAR(100) NULL     COMMENT '문의내역 작성일',
  QNA_ANSWER      VARCHAR(100) NULL     COMMENT '문의내역 답변',
  QNA_ANSWER_DATE VARCHAR(100) NULL     COMMENT '문의내역 처리일',
  ANSWER_STATUS   VARCHAR(100) NULL     COMMENT '답변상태',
  PRIMARY KEY (QNA_UID)
) COMMENT '문의내역';
